{
 "title": "Concourse: Overview",
 "tags": [ "concourse" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(concourse_workers_containers, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Builds Started",
   "type": "singlestat",
   "description": "Total number of Concourse builds started",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_started_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Finished",
   "type": "singlestat",
   "description": "Total number of Concourse builds finished",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_finished_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Succeeded",
   "type": "singlestat",
   "description": "Total number of Concourse builds succeeded",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_succeeded_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Aborted",
   "type": "singlestat",
   "description": "Total number of Concourse builds aborted",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_aborted_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Errored",
   "type": "singlestat",
   "description": "Total number of Concourse builds errored",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_errored_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Failed",
   "type": "singlestat",
   "description": "Total number of Concourse builds failed",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_failed_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Started / Finished",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_builds_started_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)",
     "legendFormat": "Started"
    },
    {
     "expr": "max(concourse_builds_finished_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)",
     "legendFormat": "Finished"
    }
   ]
  },
  {
   "title": "HTTP Response Duration",
   "type": "graph",
   "description": "HTTP response duration",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(concourse_http_responses_duration_seconds_sum{bosh_deployment=~\"$bosh_deployment\"}[5m]) / rate(concourse_http_responses_duration_seconds_count{bosh_deployment=~\"$bosh_deployment\"}[5m])) by(bosh_deployment, route)",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Builds Running",
   "type": "graph",
   "description": "Peaks correlates to active builds.\n\nObserving some leaks",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_builds_running{bosh_deployment=~\"$bosh_deployment\"} \n) \n\nby(bosh_deployment)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Worker Containers",
   "type": "graph",
   "description": "Number of containers per worker",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_containers{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Worker Volumes",
   "type": "graph",
   "description": "Number of volumes per worker",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_volumes{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "description": "Current number of concourse database connections",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_db_connections{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, dbname)",
     "legendFormat": "{{ dbname }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors by worker",
   "type": "graph",
   "description": "Current number of open file descriptors",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(process_open_fds{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU used per worker",
   "type": "graph",
   "description": "CPU seconds used",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{bosh_deployment=~\"$bosh_deployment\"}[2m])) by(bosh_deployment, instance)",
     "legendFormat": "CPU seconds"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "graph",
   "description": "Recent number of Concourse database queries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "#Concourse 3\nrate(concourse_db_queries{bosh_deployment=~\"$bosh_deployment\"}[2m])",
     "legendFormat": "Queries"
    },
    {
     "expr": "#Concourse 5\nrate(concourse_db_queries_total{bosh_deployment=~\"$bosh_deployment\"}[2m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Database locks held",
   "type": "graph",
   "description": "Database locks held, averaged in 10 mins buckets",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "checks per mins" }
   ],
   "targets": [
    {
     "expr": "sum(concourse_locks_held{bosh_deployment=~\"$bosh_deployment\"}) by (type)\n"
    }
   ]
  },
  {
   "title": "top 10 job builds ",
   "type": "graph",
   "description": "Graph shows top 10 Finished jobs averaged in 10 mins buckets.\n\nTable shows total jobs builds counter since prom restart.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "per hours" }
   ],
   "targets": [
    {
     "expr": "topk(10, # keep only top 10 to avoid eating up memory\n  max ( #over the web nodes maintaining counters\n    increase(\n        concourse_builds_finished{bosh_deployment=~\"$bosh_deployment\",status=\"succeeded\"}[1h]\n      )\n  )\n  by (exported_job) \n)\n",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Successful jobs count",
   "type": "table",
   "description": "Full count of all successful jobs executions since last concourse restart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(concourse_builds_finished{bosh_deployment=~\"$bosh_deployment\",status=\"succeeded\"}) by (pipeline, exported_job)\n",
     "legendFormat": "{{pipeline}}/{{exported_job}}"
    }
   ]
  }
 ]
}